-- Pizza Buldog: cijene, raspored dostupnosti i javna povijest promjena
create table if not exists public.menu_products (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  name text not null,
  options jsonb not null default '[]'::jsonb,
  is_visible boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique (category, name)
);

create table if not exists public.menu_price_history (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.menu_products(id) on delete cascade,
  category text not null,
  product_name text not null,
  options jsonb not null,
  is_visible boolean not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id)
);

create or replace function public.is_buldog_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

create or replace function public.record_menu_price_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' or row(new.*) is distinct from row(old.*) then
    insert into public.menu_price_history (product_id, category, product_name, options, is_visible, starts_at, ends_at, changed_by)
    values (new.id, new.category, new.name, new.options, new.is_visible, new.starts_at, new.ends_at, coalesce(new.updated_by, auth.uid()));
  end if;
  return new;
end;
$$;

drop trigger if exists menu_product_history on public.menu_products;
create trigger menu_product_history
after insert or update on public.menu_products
for each row execute function public.record_menu_price_change();

alter table public.menu_products enable row level security;
alter table public.menu_price_history enable row level security;
drop policy if exists "Public can read menu products" on public.menu_products;
create policy "Public can read menu products" on public.menu_products for select to anon, authenticated using (true);
drop policy if exists "Admins manage menu products" on public.menu_products;
create policy "Admins manage menu products" on public.menu_products for all to authenticated using (public.is_buldog_admin()) with check (public.is_buldog_admin());
drop policy if exists "Public can read menu history" on public.menu_price_history;
create policy "Public can read menu history" on public.menu_price_history for select to anon, authenticated using (true);
drop policy if exists "Admins insert menu history" on public.menu_price_history;
create policy "Admins insert menu history" on public.menu_price_history for all to authenticated using (public.is_buldog_admin()) with check (public.is_buldog_admin());
grant select on public.menu_products, public.menu_price_history to anon, authenticated;
grant insert, update, delete on public.menu_products to authenticated;

do $$
begin
  insert into public.menu_products (category, name, options) values
  ('pizze','Pizza Margherita','[{"label":"Mala","price":8.70},{"label":"Velika","price":9.60},{"label":"Jumbo","price":17.60}]'),
  ('pizze','Pizza Funghi','[{"label":"Mala","price":9.20},{"label":"Velika","price":9.60},{"label":"Jumbo","price":17.80}]'),
  ('pizze','Pizza Capricosa','[{"label":"Mala","price":9.20},{"label":"Velika","price":9.90},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Vesuvio','[{"label":"Mala","price":8.70},{"label":"Velika","price":9.70},{"label":"Jumbo","price":17.80}]'),
  ('pizze','Pizza Picante','[{"label":"Mala","price":9.20},{"label":"Velika","price":9.90},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Special','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.40},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Al Tonno','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.40},{"label":"Jumbo","price":20.00}]'),
  ('pizze','Pizza Quattro Formaggi','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Slavonska','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.70},{"label":"Jumbo","price":20.00}]'),
  ('pizze','Pizza Siciliana','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Vegetariana','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.00}]'),
  ('pizze','Pizza Frutti Di Mare','[{"label":"Mala","price":9.20},{"label":"Velika","price":11.00},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Dalmatinska','[{"label":"Mala","price":9.20},{"label":"Velika","price":11.00},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Mexicana','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Hawai','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Mozzarella','[{"label":"Mala","price":9.20},{"label":"Velika","price":11.00},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Buldog','[{"label":"Mala","price":9.20},{"label":"Velika","price":11.00},{"label":"Jumbo","price":19.50}]'),
  ('pizze','Pizza Strabiata','[{"label":"Mala","price":9.20},{"label":"Velika","price":10.50},{"label":"Jumbo","price":19.40}]'),
  ('pizze','Pizza Zagorska','[{"label":"Mala","price":9.50},{"label":"Velika","price":11.00},{"label":"Jumbo","price":20.00}]'),
  ('pizze','Pizza Gurmanska','[{"label":"Mala","price":9.20},{"label":"Velika","price":9.90},{"label":"Jumbo","price":19.40}]'),
  ('pizze','Pizza Mediterana','[{"label":"Mala","price":9.70},{"label":"Velika","price":11.20},{"label":"Jumbo","price":20.50}]'),
  ('pizze','Pizza Bianca','[{"label":"Doplata za vrhnje","price":1.00}]'),
  ('lasagne','Lasagne s Mesom','[{"label":"Standardno","price":9.00}]'),('lasagne','Lasagne Buldog','[{"label":"Standardno","price":9.00}]'),('lasagne','Lasagne sa Sirom','[{"label":"Standardno","price":8.00}]'),('lasagne','Lasagne Vegetariana','[{"label":"Standardno","price":8.00}]'),
  ('burgeri','Hamburger','[{"label":"Standardno","price":6.50},{"label":"Menu","price":7.70}]'),('burgeri','Cheeseburger','[{"label":"Standardno","price":6.50},{"label":"Menu","price":8.00}]'),('burgeri','Dupli Cheese','[{"label":"Standardno","price":8.00},{"label":"Menu","price":9.50}]'),('burgeri','American Burger','[{"label":"Standardno","price":7.00},{"label":"Menu","price":8.50}]'),('burgeri','Royal Cheese','[{"label":"Standardno","price":7.70},{"label":"Menu","price":9.50}]'),('burgeri','Chicken Burger','[{"label":"Standardno","price":7.00},{"label":"Menu","price":8.00}]'),('burgeri','Pohani Sir','[{"label":"Standardno","price":7.50}]'),('burgeri','Egg Burger','[{"label":"Doplata za jaje","price":1.00}]'),
  ('odresci','Zagrebački Odrezak','[{"label":"Standardno","price":9.00}]'),('odresci','Bečki Odrezak','[{"label":"Standardno","price":9.00}]'),('grill','Pileći ražnjići','[{"label":"Standardno","price":9.00}]'),('grill','Punjena Pljeskavica','[{"label":"Standardno","price":9.00}]'),('grill','Grill Piletina','[{"label":"Standardno","price":9.00}]'),('salate','Salata s piletinom','[{"label":"Standardno","price":9.00}]'),('salate','Kebab Salata','[{"label":"Standardno","price":9.00}]'),('pica','Pepsi Cola','[{"label":"Standardno","price":2.00}]')
  on conflict (category, name) do nothing;
end $$;

notify pgrst, 'reload schema';
